apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: catalog-comparison-service
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/iap-enabled: 'true'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
    spec:
      serviceAccountName: catalog-agent-sa@fde-bestbuy-sandbox-dev-508321.iam.gserviceaccount.com
      containerConcurrency: 80
      containers:
        - image: us-central1-docker.pkg.dev/fde-bestbuy-sandbox-dev-508321/catalog-agent-repo/backend:latest
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          env:
            - name: GCP_PROJECT_ID
              value: fde-bestbuy-sandbox-dev-508321
            - name: ENVIRONMENT
              value: production
            - name: BIGQUERY_DATASET
              value: catalog
            - name: BIGQUERY_CATALOG_TABLE
              value: products
            - name: BIGQUERY_TELEMETRY_DATASET
              value: catalog_agent_telemetry
            - name: BIGQUERY_TELEMETRY_TABLE
              value: query_telemetry
            - name: EXPORT_TRACES_TO_CLOUD
              value: "true"
            - name: AGENT_RUNTIME_RESOURCE_NAME
              value: "projects/499572810092/locations/us-central1/reasoningEngines/2445220951441276928"
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 24
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 15
